ARG PYTHON_VERSION="3.12-trixie"

# FRONT BUILDING
FROM oven/bun:debian AS frontend-builder
COPY frontend/ /app/
WORKDIR /app
# hadolint ignore=DL3008
RUN bun install --frozen-lockfile --ignore-scripts && bun run generate

# BACK BUILDING
FROM ghcr.io/astral-sh/uv:python${PYTHON_VERSION} AS backend-builder

# hadolint ignore=DL3008
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    libpq-dev=17.* \
    unixodbc-dev=2.* \
    g++=4:* \
    libssl-dev=3.* \
    curl=8.* \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /tmp
COPY backend/pyproject.toml backend/uv.lock /tmp/
SHELL ["/bin/bash", "-o", "pipefail", "-c"]

RUN pip install -U --no-cache-dir pip==25.3 \
 && export PATH="/root/.local/bin:$PATH" \
 && uv export --format requirements.txt --output-file requirements.txt \
 && echo "psycopg2-binary==2.8.6" >> /requirements.txt \
 && echo "django-heroku==0.3.1" >> /requirements.txt \
 && pip install --no-cache-dir -r /requirements.txt


# FINAL IMAGE
FROM python:${PYTHON_VERSION} AS runtime

RUN apt-get update \
 && apt-get install -y --no-install-recommends \
    libpq-dev=17.* \
    unixodbc-dev=2.* \
    libssl-dev=3.* \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/sh doccano
RUN mkdir /data \
 && chown doccano:doccano /data

COPY --from=backend-builder /usr/local/lib/python3.12/site-packages /usr/local/lib/python3.12/site-packages
COPY --from=backend-builder /usr/local/bin/celery /usr/local/bin/celery
COPY --from=backend-builder /usr/local/bin/gunicorn /usr/local/bin/gunicorn

COPY --chown=doccano:doccano . /doccano
WORKDIR /doccano/backend
COPY --from=frontend-builder /app/apps/frontend/.output/public /doccano/backend/client/dist
RUN uv run src/manage.py collectstatic --noinput \
 && chown -R doccano:doccano .

VOLUME /data
ENV DATABASE_URL="sqlite:////data/doccano.db"

ENV DEBUG="False"
ENV STANDALONE="True"
ENV SECRET_KEY="change-me-in-production"
ENV PORT="8000"
ENV WORKERS="2"
ENV CELERY_WORKERS="2"
ENV DJANGO_SETTINGS_MODULE="config.settings.production"

USER doccano
EXPOSE ${PORT}

CMD ["/doccano/tools/run.sh"]
